### ISSUE TITLE
Create GSoC org browser

### ISSUE THREAD

**Issue by jayvdb** [gsocindonesia/gsocindonesia.github.io#6]
Create a new static webapp in a new repository that provides an innovative user interface for the information currently available at 
https://summerofcode.withgoogle.com/organization/
using the raw data available at

https://summerofcode.withgoogle.com/api/program/current/organization/
and
https://summerofcode.withgoogle.com/api/program/current/

The [GCI leaders webapp](https://github.com/coala/gci-leaders/) may be useful as a guide for how to build it.  It was built almost entirely by high school students, and ~50% by Indonesian high school students. ;-)

**Comment by ceefour** [comment]
Terima kasih @jayvdb for the initial jumpkick. 

Next I hope we can interest students to make small chunks of contribution here and there.

**Comment by jayvdb** [comment]
Done at https://github.com/gsocindonesia/gsoc-orgs/
